server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
    database: mysql
    show-sql: true
    generate-ddl: true
  redis:
    host: pongponglabs.iptime.org
    port: 6379
    database: 0
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pongponglabs.iptime.org:3306/EYEAR?serverTimezone=UTC&characterEncoding=UTF-8
    username: depark
    password: pongponglabs

springdoc:
  version: '1.0.0'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  packages-to-scan: pnu.classplus.controller
  paths-to-match:
    - /member/**
    - /info/**
    - /admin2/**
    - /student/**

# App Properties
eyear:
  app:
    jwtSecretKey: jwtEyearSecretKey